services:
  planesign:
    image: ghcr.io/dmod/planesign:latest
    container_name: PlaneSignRuntime
    restart: unless-stopped
    stop_grace_period: 90s
    privileged: true
    network_mode: host
    volumes:
      - ./sign.conf:/planesign/sign.conf
      - ./datafiles:/planesign/datafiles
      - ./sketches:/planesign/sketches
      - ./icons:/planesign/icons
