[project]
name = "planesign"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "country-converter>=1.3.2",
    "favicon>=0.7.0",
    "finnhub-python>=2.4.28",
    "flask>=3.1.3",
    "flask-cors>=6.0.5",
    "geopandas>=1.1.4",
    "gevent>=26.4.0",
    "numba>=0.65.1",
    "numpy>=2.4.4",
    "pillow>=12.3.0",
    "pytz>=2026.2",
    "requests>=2.34.2",
    "rgbmatrix",
    "skyfield>=1.54",
    "timezonefinder>=8.2.4",
    "websocket-client>=1.9.0",
    "websockets>=15.0",
]

[tool.ruff]
line-length = 300

[tool.ruff.lint]
ignore = ["LOG015", "RUF023"]

[tool.ruff.format]
skip-magic-trailing-comma = true

[tool.uv.sources]
rgbmatrix = { git = "https://github.com/hzeller/rpi-rgb-led-matrix.git", rev = "41809e40e912b7f278ad34046f20abf5609b2b07" }
