name: CI to Docker Hub

on:
  push:
    tags:
      - "v*.*.*"

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        run: docker buildx build \
            --platform linux/arm/v7 \
            --tag ${{ secrets.DOCKER_HUB_USERNAME }}/planesign:latest \
            --file ./Dockerfile \
            --output type=image,push=true .

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
